"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class ax_control_t(object):
    __slots__ = ["source", "front", "sig_l", "sig_r", "brake", "hazard", "showoff"]

    def __init__(self):
        self.source = ""
        self.front = False
        self.sig_l = False
        self.sig_r = False
        self.brake = False
        self.hazard = False
        self.showoff = 0

    def encode(self):
        buf = BytesIO()
        buf.write(ax_control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __source_encoded = self.source.encode('utf-8')
        buf.write(struct.pack('>I', len(__source_encoded)+1))
        buf.write(__source_encoded)
        buf.write(b"\0")
        buf.write(struct.pack(">bbbbbb", self.front, self.sig_l, self.sig_r, self.brake, self.hazard, self.showoff))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != ax_control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return ax_control_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = ax_control_t()
        __source_len = struct.unpack('>I', buf.read(4))[0]
        self.source = buf.read(__source_len)[:-1].decode('utf-8', 'replace')
        self.front = bool(struct.unpack('b', buf.read(1))[0])
        self.sig_l = bool(struct.unpack('b', buf.read(1))[0])
        self.sig_r = bool(struct.unpack('b', buf.read(1))[0])
        self.brake = bool(struct.unpack('b', buf.read(1))[0])
        self.hazard = bool(struct.unpack('b', buf.read(1))[0])
        self.showoff = struct.unpack(">b", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if ax_control_t in parents: return 0
        tmphash = (0x9d29638ecffc2a70) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if ax_control_t._packed_fingerprint is None:
            ax_control_t._packed_fingerprint = struct.pack(">Q", ax_control_t._get_hash_recursive([]))
        return ax_control_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

