"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class eng_status_t(object):
    __slots__ = ["running", "temp", "pressure", "rpm", "fuel_flow"]

    def __init__(self):
        self.running = False
        self.temp = 0
        self.pressure = 0
        self.rpm = 0
        self.fuel_flow = 0

    def encode(self):
        buf = BytesIO()
        buf.write(eng_status_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bhhhh", self.running, self.temp, self.pressure, self.rpm, self.fuel_flow))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != eng_status_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return eng_status_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = eng_status_t()
        self.running = bool(struct.unpack('b', buf.read(1))[0])
        self.temp, self.pressure, self.rpm, self.fuel_flow = struct.unpack(">hhhh", buf.read(8))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if eng_status_t in parents: return 0
        tmphash = (0x8f7cfbdf951395b5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if eng_status_t._packed_fingerprint is None:
            eng_status_t._packed_fingerprint = struct.pack(">Q", eng_status_t._get_hash_recursive([]))
        return eng_status_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

