"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class log_control_t(object):
    __slots__ = ["recording"]

    def __init__(self):
        self.recording = False

    def encode(self):
        buf = BytesIO()
        buf.write(log_control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.recording))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != log_control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return log_control_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = log_control_t()
        self.recording = bool(struct.unpack('b', buf.read(1))[0])
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if log_control_t in parents: return 0
        tmphash = (0xd696b7b5e76329a4) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if log_control_t._packed_fingerprint is None:
            log_control_t._packed_fingerprint = struct.pack(">Q", log_control_t._get_hash_recursive([]))
        return log_control_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

