"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class cam_feed_t(object):
    __slots__ = ["feed_running", "frame"]

    def __init__(self):
        self.feed_running = False
        self.frame = 0

    def encode(self):
        buf = BytesIO()
        buf.write(cam_feed_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">bB", self.feed_running, self.frame))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != cam_feed_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return cam_feed_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = cam_feed_t()
        self.feed_running = bool(struct.unpack('b', buf.read(1))[0])
        self.frame = struct.unpack(">B", buf.read(1))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if cam_feed_t in parents: return 0
        tmphash = (0xd1bbfec7f2bd53eb) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if cam_feed_t._packed_fingerprint is None:
            cam_feed_t._packed_fingerprint = struct.pack(">Q", cam_feed_t._get_hash_recursive([]))
        return cam_feed_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

