"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class mode_control_t(object):
    __slots__ = ["evos_mode"]

    def __init__(self):
        self.evos_mode = ""

    def encode(self):
        buf = BytesIO()
        buf.write(mode_control_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        __evos_mode_encoded = self.evos_mode.encode('utf-8')
        buf.write(struct.pack('>I', len(__evos_mode_encoded)+1))
        buf.write(__evos_mode_encoded)
        buf.write(b"\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != mode_control_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return mode_control_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = mode_control_t()
        __evos_mode_len = struct.unpack('>I', buf.read(4))[0]
        self.evos_mode = buf.read(__evos_mode_len)[:-1].decode('utf-8', 'replace')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if mode_control_t in parents: return 0
        tmphash = (0xf3525c1f352d555f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if mode_control_t._packed_fingerprint is None:
            mode_control_t._packed_fingerprint = struct.pack(">Q", mode_control_t._get_hash_recursive([]))
        return mode_control_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

